name: Run Command on EC2

on:
  push:
    branches:
      - main

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Command on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.211.32.220 "echo 'Hello PearlThoughts...' > output.txt 2>&1"
